# Generated by Django 3.1.7 on 2021-04-27 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)])),
                ('student_name', models.CharField(max_length=30)),
                ('fathers_name', models.CharField(max_length=30)),
                ('dob', models.DateField(help_text='format : DD-MM-YYYY', max_length=10)),
                ('mobile', models.IntegerField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('email', models.EmailField(max_length=50)),
                ('room_no', models.CharField(max_length=5)),
            ],
        ),
    ]
