# Generated by Django 3.1.7 on 2021-04-27 08:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)])),
                ('dob', models.DateField(help_text='format : DD-MM-YYYY', max_length=10)),
                ('mobile', models.IntegerField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('room_no', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=150)),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostel.students')),
            ],
        ),
    ]
