# Generated by Django 3.1.7 on 2021-04-28 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('full_name', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('dob', models.DateField(auto_now_add=True, help_text='format : DD-MM-YYYY', max_length=10)),
                ('mobile', models.IntegerField()),
                ('room_no', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=20)),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostel.student')),
            ],
        ),
    ]
