# Generated by Django 3.1.7 on 2021-04-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
