# Generated by Django 3.1.7 on 2021-04-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0002_auto_20210427_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='roll_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
