# Generated by Django 3.1.7 on 2021-04-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0002_auto_20210429_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='roll_no',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
