# Generated by Django 3.1.7 on 2021-04-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0003_auto_20210429_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
