# Generated by Django 3.1.7 on 2021-04-27 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0003_auto_20210428_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='rollno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Hostel.students'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
