# Generated by Django 3.1.7 on 2021-04-27 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0004_auto_20210428_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='rollno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostel.students'),
        ),
    ]
