# Generated by Django 3.1.7 on 2021-04-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0005_auto_20210428_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='full_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
