# Generated by Django 3.1.7 on 2021-04-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0006_auto_20210428_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='dob',
            field=models.DateField(auto_now_add=True, help_text='format : DD-MM-YYYY', max_length=10),
        ),
    ]
