# Generated by Django 3.1.7 on 2021-05-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0006_auto_20210502_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
